print("Yeh Calculator Hai Bhai")
print("-----------------------")
#EXAMPLE ADDITION 
num1 = input("Enter Number 1:") #Yeh String Hai Samjhe 
num2 = input("Enter Number 2:") #Yeh bhi String Samjha

n1 = int (num1) #conversion
n2 = int (num2) #conversion

sum = n1 + n2
print("\nAddition :",sum) #Sum kaa program  hai Abhijeet

sub = n1 - n2
print("\nsubtraction:", sub) #Sub Kam Program Hai Abhi bhai

mult = n1 * n2
print("\nmultiplication:",mult) #Multi Ka Program Hai Abhi 

div = n1 / n2
print("\nDivision Value:",div) #Div Ka Program Hai abhi

rem = float(n1) % float(n2) #Renaider Ka program Hai Abhi
print("\nRemainder :",rem)